
const allModifiersData = {
    "1x1": {
        prefixes: [
            "Your Maps have +(15–25)% chance to contain an Abyss (2000)",
            "Your Maps have (80–100)% increased chance to contain an Abyss (2000)",
            "Your Maps have +(15–25)% chance to contain Alva (1500)",
            "Your Maps have (80–100)% increased chance to contain Alva (1500)",
            "Your Maps have a (15–25)% chance to contain an additional Rogue Exile (500)",
            "Your Maps have +(7–10)% chance to contain a Rogue Exile (1000)",
            "Map Bosses have (6–10)% chance to be accompanied by two Rogue Exile Bodyguards (500)",
            "Map Bosses have (2–3)% chance to be accompanied by two Rogue Exiles (1000)",
            "Your Maps have +(15–25)% chance to contain Einhar (1500)",
            "Your Maps have (80–100)% increased chance to contain Einhar (1500)",
            "(15–25)% chance for your Maps to attract Beyond Demons (1000)",
            "Your Maps have +(15–25)% chance to contain a Blight Encounter (2000)",
            "Your Maps have (80–100)% increased chance to contain a Blight Encounter (2000)",
            "Your Maps have +(15–25)% chance to contain Breaches (1000)",
            "Your Maps have (80–100)% increased chance to contain a Breach (2000)",
            "Your Maps which contain Breaches have (15–25)% chance to contain an additional Breach (1000)",
            "Map Bosses have (40–60)% increased chance to drop a Conqueror Map (1000)",
            "Your Maps have +(15–25)% chance to contain a Mirror of Delirium (2000)",
            "Your Maps have (80–100)% increased chance to contain a Mirror of Delirium (2000)",
            "Your Maps have +(15–25)% chance to contain Niko (600)",
            "Your Maps have (80–100)% increased chance to contain Niko (1500)",
            "Your White Tier Maps grant (100–150) additional Voltaxic Sulphite on Completion (300)",
            "Your Yellow Tier Maps grant (150–200) additional Voltaxic Sulphite on Completion (300)",
            "Your Red Tier Maps grant (200–250) additional Voltaxic Sulphite on Completion (300)",
            "Your Maps have +(7–10)% chance to contain a Shrine (1000)",
            "Your Maps have a (35–50)% chance to contain an additional Shrine (1000)",
            "Your Maps have +(7–10)% chance to contain an Imprisoned Monster (1000)",
            "Your Maps have (35–50)% chance to contain an additional Imprisoned Monster (1000)",
            "Your Maps have +(15–25)% chance to contain an Expedition Encounter (2000)",
            "Your Maps have (80–100)% increased chance to contain an Expedition Encounter (2000)",
            "Your Maps have a (35–50)% chance to contain an additional Harbinger (1000)",
            "Your Maps have +(15–25)% chance to contain The Sacred Grove (2000)",
            "Your Maps have (80–100)% increased chance to contain The Sacred Grove (2000)",
            "Your Maps have +(15–25)% chance to contain a Smuggler's Cache (1000)",
            "Your Maps have (80–100)% increased chance to contain a Smuggler's Cache (2000)",
            "(10–15)% increased Heist Contracts found in your Maps (1000)",
            "Your Maps have +(15–25)% chance to contain Jun (1500)",
            "Your Maps have (80–100)% increased chance to contain Jun (1500)",
            "Your Maps have +(15–25)% chance to contain a Legion Encounter (2000)",
            "Your Maps have (80–100)% increased chance to contain a Legion Encounter (2000)",
            "Tier 1-15 Maps found have (5–10)% chance to become 1 tier higher (1000)",
            "Your Maps have (80–100)% increased chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(15–25)% chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(15–25)% chance to contain Ritual Altars (2000)",
            "Your Maps have (80–100)% increased chance to contain Ritual Altars (2000)",
            "(5–10)% increased Scarabs found in your Maps (1000)",
            "Your Maps have +(35–50)% chance to contain a Strongbox (1000)",
            "Your Maps have a (35–50)% chance to be haunted by an additional Tormented Spirit (1000)",
            "Your Maps have +(7–10)% chance to be haunted by a Tormented Spirit (1000)",
            "(10–15)% increased Atlas Scouting Reports found in your Maps (1000)",
            "(2–3)% increased Maps found in Area (1000)",
            "Your Maps contain (3–5)% more Monster Packs consisting of difficult and rewarding Monsters (1000)"
        ],
        suffixes: [
            "Abyssal Troves and Stygian Spires in your Maps have (15–25)% increased chance to contain or drop an Abyss Jewel (1000)",
            "Abyssal Troves and Stygian Spires in your Maps have (6–10)% chance to drop a Rare Item with an Abyssal Socket (1000)",
            "(300–350)% increased Rarity of Items Dropped by Abyssal Troves and Stygian Spires in your Maps (1000)",
            "Incursions in your Maps have (4–6)% increased Pack Size (1500)",
            "(5–10)% chance to create a copy of Beasts Captured in your Maps (500)",
            "Red Beasts in your Maps have (40–60)% increased chance to be from The Deep (250)",
            "Red Beasts in your Maps have (40–60)% increased chance to be from The Wilds (250)",
            "Red Beasts in your Maps have (40–60)% increased chance to be from The Caverns (250)",
            "Red Beasts in your Maps have (40–60)% increased chance to be from The Sands (250)",
            "Beyond Demons in your Maps have (35–45)% increased chance to be followers of K'tash (333)",
            "Beyond Demons in your Maps have (35–45)% increased chance to be followers of Beidat (333)",
            "Beyond Demons in your Maps have (35–45)% increased chance to be followers of Ghorr (333)",
            "(15–20)% reduced Cost of Building and Upgrading Towers (800)",
            "Blight Chests in your Maps have (15–25)% more chance to contain Blighted Maps (1200)",
            "Breaches in your Maps spawn (15–20)% increased Magic Monsters (600)",
            "Chayula, Who Dreamt in your Maps has a (20–30)% chance to be Duplicated (200)",
            "Esh, Forked Thought in your Maps has a (20–30)% chance to be Duplicated (200)",
            "Uul-Netol, Unburdened Flesh in your Maps has a (20–30)% chance to be Duplicated (200)",
            "Xoph, Dark Embers in your Maps has a (20–30)% chance to be Duplicated (200)",
            "Tul, Creeping Avalanche in your Maps has a (20–30)% chance to be Duplicated (200)",
            "Breaches in your Maps have (35–45)% increased chance to contain a Breach Boss' Clasped Hand (400)",
            "Monster Packs Influenced by The Searing Exarch in your Maps have (4–6)% increased Pack Size (1000)",
            "Delirium Encounters in your Maps have (6–10)% chance to generate an additional Reward type (200)",
            "Delirium Encounters in your Maps are (35–50)% more likely to spawn Unique Bosses (400)",
            "Delirium Bosses in your Maps drop (20–30)% increased Simulacrum Splinters (500)",
            "Delirious Monsters Killed in your Maps provide (10–20)% increased Reward Progress (400)",
            "Delirium Monsters in your Maps have (5–10)% increased Pack Size (500)",
            "Sulphite Veins and Chests in your Maps have (3–5)% chance to also contain an equal amount of Azurite (1500)",
            "(30–40)% increased Duration of Shrine Effects on Players in your Maps (1000)",
            "Imprisoned Monsters in your Maps have (40–60)% chance to drop an additional Rare Item with an Essence Modifier (500)",
            "Imprisoned Monsters in your Maps have (8–12)% chance to have an additional Essence (500)",
            "(15–20)% increased Explosive Radius in your Maps (1000)",
            "(15–25)% increased Quantity of Expedition Logbooks dropped by Runic Monsters in your Maps (1000)",
            "Harbingers in your Maps have (20–30)% increased Cooldown Recovery Rate (1000)",
            "Harvest Monsters in your Maps grant (70–90)% increased Experience (1100)",
            "Harvest Crops in your Maps have (10–15)% reduced chance to grow Yellow Plants (300)",
            "Harvest Crops in your Maps have (10–15)% reduced chance to grow Blue Plants (300)",
            "Harvest Crops in your Maps have (10–15)% reduced chance to grow Purple Plants (300)",
            "Smuggler's Caches in your Maps have (35–45)% increased chance to drop Blueprints (800)",
            "Heist Contracts found in your Maps are (40–60)% more likely to require Lockpicking, Brute Force or Perception (400)",
            "Heist Contracts found in your Maps are (40–60)% more likely to require Demolition, Counter-Thaumaturgy or Trap Disarmament (400)",
            "Heist Contracts found in your Maps are (40–60)% more likely to require Agility, Deception or Engineering (400)",
            "Immortal Syndicate Members in your Maps are (40–60)% more likely to be accompanied by their Leader (1000)",
            "Immortal Syndicate Members Executed in your Maps have (40–60)% chance to gain an additional Rank (1000)",
            "Legion Sergeants in your Maps have (6–10)% additional chance to have Rewards (500)",
            "Legion Encounters in your Maps are (25–35)% more likely to include a General (750)",
            "Legion Chests released from Stasis in your Maps release other Monsters and Chests with (35–50)% increased Range (750)",
            "Ultimatum Encounters in your Maps have (15–20)% increased chance for the final Round to include a Boss (600)",
            "Ultimatum Encounters in your Maps have (40–60)% increased chance to require you to protect the Altar (200)",
            "Ultimatum Rewards in your Maps have (20–30)% increased chance to be Unique Items (200)",
            "Ultimatum Rewards in your Maps have (20–30)% increased chance to be Jewellery (200)",
            "Ultimatum Rewards in your Maps have (20–30)% increased chance to be Currency Items (200)",
            "Ultimatum Encounters in your Maps have (40–60)% increased chance to require you to defeat waves of Enemies (200)",
            "Ultimatum Encounters in your Maps have (40–60)% increased chance to require you to Stand in the Stone Circles (200)",
            "Ultimatum Rewards in your Maps have (20–30)% increased chance to be Divination Cards (200)",
            "Ultimatum Rewards in your Maps have (20–30)% increased chance to be Gems (200)",
            "Ultimatum Encounters in your Maps have (40–60)% increased chance to only require you to Survive (200)",
            "Rerolling Favours at Ritual Altars in your Maps costs (8–12)% reduced Tribute (400)",
            "Favours Deferred at Ritual Altars in your Maps reappear (20–30)% sooner (800)",
            "Unique Monsters slain at Ritual Altars in your Maps grant (40–60)% more Tribute (800)",
            "Unique Monsters in your Maps have (75–100)% increased chance to drop Scarabs (500)",
            "Strongboxes in your Maps have (50–70)% increased chance to be an Arcanist's Strongbox (333)",
            "Strongboxes in your Maps have (50–70)% increased chance to be a Cartographer's Strongbox (333)",
            "Strongboxes in your Maps have (50–70)% increased chance to be a Diviner's Strongbox (333)",
            "Strongboxes in your Maps have (40–60)% increased chance to be a Gemcutter's Strongbox (333)",
            "Your Maps have (4–6)% chance to award double progress towards encountering The Eater of Worlds (500)",
            "Eldritch Ichor found in your Maps influenced by The Eater of Worlds have (4–6)% chance to be Duplicated (500)",
            "Tormented Spirits in your Maps have (40–60)% increased Duration (1000)",
            "Items found in your Corrupted Maps have (1–2)% chance to be Corrupted (500)",
            "Vaal Side Areas in your Maps have (6–10)% chance to be an Alluring Vaal Side Area (500)",
            "Items dropped by Rare Monsters have (3–5)% chance to be Corrupted (500)",
            "(2–4)% chance for Scouting Reports to drop as Otherworldly Scouting Reports instead in your Maps (400)",
            "(2–4)% chance for Scouting Reports to drop as Delirious Scouting Reports instead in your Maps (400)",
            "(2–4)% chance for Scouting Reports to drop as Blighted Scouting Reports instead in your Maps (400)",
            "(6–10)% chance for Scouting Reports to drop as Comprehensive Scouting Reports instead in your Maps (400)",
            "(4–6)% chance for Scouting Reports to drop as Vaal Scouting Reports instead in your Maps (400)",
            "(3–5)% chance for Scouting Reports to drop as Operative's Scouting Reports instead in your Maps (400)",
            "(4–6)% chance for Scouting Reports to drop as Singular Scouting Reports instead in your Maps (400)"
        ]
    },
    "2x1": {
        prefixes: [
            "Your Maps have +(30–45)% chance to contain an Abyss (2000)",
            "Your Maps have (144–180)% increased chance to contain an Abyss (2000)",
            "Your Maps have +(30–45)% chance to contain Alva (1500)",
            "Your Maps have (144–180)% increased chance to contain Alva (1500)",
            "Your Maps have a (30–45)% chance to contain an additional Rogue Exile (1000)",
            "Your Maps have +(12–18)% chance to contain a Rogue Exile (1000)",
            "Your Maps have +(30–45)% chance to contain Einhar (1500)",
            "Your Maps have (144–180)% increased chance to contain Einhar (1500)",
            "(30–45)% chance for your Maps to attract Beyond Demons (1000)",
            "Your Maps have +(30–45)% chance to contain a Blight Encounter (2000)",
            "Your Maps have (144–180)% increased chance to contain a Blight Encounter (2000)",
            "Your Maps have +(30–45)% chance to contain Breaches (1000)",
            "Your Maps have (144–180)% increased chance to contain a Breach (2000)",
            "Your Maps which contain Breaches have (5–10)% chance to contain two additional Breaches (1000)",
            "Your Maps have +(30–45)% chance to contain a Mirror of Delirium (2000)",
            "Your Maps have (144–180)% increased chance to contain a Mirror of Delirium (2000)",
            "Your Maps have +(30–45)% chance to contain Niko (1500)",
            "Your Maps have (144–180)% increased chance to contain Niko (1500)",
            "Your Maps have +(12–18)% chance to contain a Shrine (1000)",
            "Your Maps have a (60–80)% chance to contain an additional Shrine (1000)",
            "Final Map Boss in each Map has +(1.8–2.4)% chance to drop a Shaper Guardian Map (Tier 14+) (1000)",
            "Final Map Boss in each Map has +(1.8–2.4)% chance to drop an Elder Guardian Map (Tier 14+) (1000)",
            "Your Maps have +(12–18)% chance to contain an Imprisoned Monster (1000)",
            "Your Maps have (60–80)% chance to contain an additional Imprisoned Monster (1000)",
            "Your Maps have +(30–45)% chance to contain an Expedition Encounter (2000)",
            "Your Maps have (144–180)% increased chance to contain an Expedition Encounter (2000)",
            "Your Maps have a (60–80)% chance to contain an additional Harbinger (1000)",
            "Your Maps have +(30–45)% chance to contain The Sacred Grove (2000)",
            "Your Maps have (144–180)% increased chance to contain The Sacred Grove (2000)",
            "Your Maps have +(30–45)% chance to contain a Smuggler's Cache (2000)",
            "Your Maps have (144–180)% increased chance to contain a Smuggler's Cache (2000)",
            "(20–25)% increased Blueprints found in your Maps (400)",
            "Your Maps have +(30–45)% chance to contain Jun (1500)",
            "Your Maps have (144–180)% increased chance to contain Jun (1500)",
            "Your Maps have +(30–45)% chance to contain a Legion Encounter (2000)",
            "Your Maps have (144–180)% increased chance to contain a Legion Encounter (2000)",
            "Your Maps have (144–180)% increased chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(30–45)% chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(30–45)% chance to contain Ritual Altars (2000)",
            "Your Maps have (144–180)% increased chance to contain Ritual Altars (2000)",
            "Your Maps have +(60–80)% chance to contain a Strongbox (1000)",
            "+(1.2–1.8)% chance for a Synthesis Map to drop from Final Map Boss in each Map (Tier 14+) (1000)",
            "Your Maps have a (60–80)% chance to be haunted by an additional Tormented Spirit (1000)",
            "Your Maps have +(12–18)% chance to be haunted by a Tormented Spirit (1000)",
            "Map Bosses have (6–8)% chance to be surrounded by Tormented Spirits (1000)",
            "Your Maps have +(5–8)% chance to contain a Vaal Side Area (1000)",
            "(5–8)% chance for one Monster in each of your Maps to drop an additional connected Map (1000)"
        ],
        suffixes: [
            "Abysses in your Maps spawn (12–18)% increased Monsters (400)",
            "Abyss Monsters in your Maps grant (30–40)% increased Experience (400)",
            "Abyss Cracks in your Maps have (8–12)% chance to spawn 100% increased Monsters (400)",
            "Abyss Pits in your Maps have (8–12)% chance to spawn 100% increased Monsters (400)",
            "Abyss Cracks in your Maps have (3–5)% chance to spawn all Monsters as Magic for each prior Pit in that Abyss (400)",
            "Incursions in your Maps have (15–25)% chance for all Monsters to be at least Magic (1500)",
            "(30–40)% increased Rarity of Items Dropped by Wild Rogue Exiles in your Maps (1000)",
            "Rogue Exiles in your Maps have (15–20)% chance to drop an additional Currency Item (1000)",
            "Your Maps that contain capturable Beasts have (12–18)% chance to contain an additional Red Beast (700)",
            "Einhar deals (600–800)% more Damage to Unique Monsters in your Maps (400)",
            "Einhar has (60–80)% increased Cooldown Recovery Rate in your Maps (400)",
            "Beyond Portals in your Maps have (20–25)% increased Merging Radius (500)",
            "(10–15)% increased Quantity of Tainted Currency dropped by Beyond Demons in your Maps (500)",
            "Lanes of Blight Encounters in your Maps have (6–8)% chance for an additional Reward Chest (600)",
            "(15–25)% chance for Blight Chests to contain an additional Reward (400)",
            "Blight Bosses in your Maps have (14–18)% chance to add an additional Reward Chest when Defeated (400)",
            "Blighted Chests in your Maps have (25–35)% increased chance to contain an Oil (600)",
            "Blight Monsters in your Maps spawn (40–60)% faster (600)",
            "Breach Bosses in your Maps have (12–16)% chance to drop double Breach Splinters (300)",
            "(20–25)% increased Quantity of Breach Splinters found in Breach Hands in your Maps (300)",
            "Breaches in your Maps have (80–120)% increased chance to belong to Xoph (160)",
            "Breaches in your Maps have (80–120)% increased chance to belong to Tul (160)",
            "Breaches in your Maps have (80–120)% increased chance to belong to Esh (160)",
            "Breaches in your Maps have (70–100)% increased chance to belong to Uul-Netol (160)",
            "Breaches in your Maps have (60–80)% increased chance to belong to Chayula (160)",
            "(20–25)% increased Quantity of Breach Splinters dropped by Breach Monsters in your Maps (300)",
            "Breach Monsters in your Maps have (3–7)% increased chance to drop a Breach Unique Item (300)",
            "Monsters Influenced by The Searing Exarch in your Maps have (0.5–0.7)% chance to drop an Item with a Searing Exarch Implicit Modifier (1000)",
            "Monster Packs Influenced by Conquerors in your Maps have (8–12)% increased Pack Size (500)",
            "Delirium Fog in your Maps dissipates (2–5)% slower (600)",
            "Delirium Bosses in your Maps have (30–40)% increased chance to drop Unique Cluster Jewels (500)",
            "Delirium Monsters in your Maps have (15–25)% increased chance to drop Cluster Jewels (300)",
            "Cluster Jewels from Delirium Rewards have a (6–8)% chance to be Rare and Corrupted (600)",
            "Voltaxic Sulphite Veins and Chests in your Maps contain (8–10)% increased Sulphite (1000)",
            "You Gain (8–12)% increased Movement Speed per stack of Sulphite Intoxication. (500)",
            "(25–35)% increased Effect of Shrine Buffs on Players in your Maps (1000)",
            "Monsters Imprisoned by Essences have a (20–25)% chance to contain a Remnant of Corruption (1000)",
            "(10–15)% increased quantity of Artifacts dropped by Monsters (600)",
            "(6–10)% increased number of Explosives in your Maps (600)",
            "(15–20)% increased Quantity of Vendor Refresh Currencies dropped by Monsters in your Maps (400)",
            "Expedition Detonation Chains in your Maps travel (12–18)% slower (400)",
            "Harbingers in your Maps have (40–60)% chance to drop an additional Stack of Currency Shards (1000)",
            "Harvest Crops in your Maps have (35–45)% increased chance to contain a Tier 4 Plant (1000)",
            "Harvest Crops in your Maps have (25–35)% increased chance to contain Tier 3 Plants (1000)",
            "Heist Contracts found in your Maps are (75–125)% more likely to require level 3 Jobs (400)",
            "Heist Contracts found in your Maps are (75–125)% more likely to require level 4 Jobs (400)",
            "Heist Contracts found in your Maps are (75–125)% more likely to require level 5 Jobs (400)",
            "Your Maps that contain Smuggler's Caches have a (25–35)% chance to contain an additional Smuggler's Cache (400)",
            "Immortal Syndicate Members in your Maps are (120–160)% more likely to offer to Bargain for Items (750)",
            "(16–24)% increased Rarity of items from Defeated Syndicate Members in your Maps per Equipment Item they have (750)",
            "(100–150)% increased Rarity of Items Dropped by Legion Sergeants in your Maps (500)",
            "Legion Encounters in your Maps have (40–60)% increased Duration (500)",
            "Legion Monsters in your Maps take (30–40)% increased Damage while in Stasis (500)",
            "Legion Monsters in your Maps have (10–15)% increased Pack Size (500)",
            "Ultimatum Altars in your Maps have (30–40)% increased Life (300)",
            "Ultimatum Stone Circles in your Maps have (15–20)% increased radius (300)",
            "Ultimatum Rewards in your Maps have (25–35)% increased chance to be Inscribed Ultimatums (800)",
            "Ultimatum Encounters in your Maps only requiring you to Survive have (3–5)% reduced duration (300)",
            "Ultimatum Encounters in your Maps requiring you to Defeat waves of Enemies require killing (3–5)% reduced number of Enemies (300)",
            "(50–75)% increased chance of Ritual Altars with Special Rewards (800)",
            "Favours Rerolled at Ritual Altars in your Maps have (0.8–1.2)% chance to cost no Tribute (200)",
            "Ritual Altars in your Maps can have (15–25)% increased number of Spawned Monsters at once (500)",
            "Ritual Splinters offered at Ritual Altars in your Maps have (20–25)% increased Stack Size (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Cartography Scarabs (500)",
            "Scarabs found in your Maps are (60–80)% more likely to be Ambush Scarabs (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Titanic Scarabs (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Harbinger Scarabs (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Beyond Scarabs (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Essence Scarabs (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Torment Scarabs (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Domination Scarabs (500)",
            "Scarabs dropped in your Maps are (60–80)% more likely to be Anarchy Scarabs (500)",
            "Strongboxes in your Maps have (40–60)% chance to be guarded by an additional Pack of Monsters (500)",
            "(15–20)% increased Quantity of Items contained in Strongboxes in your Maps (500)",
            "Tormented Spirits have a (1–2)% chance to be set free when Possessed Monsters are slai (1000)"
        ]
    },
    "1x2": {
        prefixes: [],
        suffixes: []
    },
    "3x1": {
        prefixes: [
            "Your Maps have +(40–60)% chance to contain an Abyss (2000)",
            "Your Maps have (192–240)% increased chance to contain an Abyss (2000)",
            "Your Maps have +(40–60)% chance to contain Alva (1500)",
            "Your Maps have (192–240)% increased chance to contain Alva (1500)",
            "Your Maps have a (40–60)% chance to contain an additional Rogue Exile (1000)",
            "Your Maps have +(15–25)% chance to contain a Rogue Exile (1000)",
            "Your Maps have +(40–60)% chance to contain Einhar (1500)",
            "Your Maps have (192–240)% increased chance to contain Einhar (1500)",
            "(40–60)% chance for your Maps to attract Beyond Demons (1000)",
            "Your Maps have +(40–60)% chance to contain a Blight Encounter (2000)",
            "Your Maps have (192–240)% increased chance to contain a Blight Encounter (2000)",
            "Your Maps have +(40–60)% chance to contain Breaches (1200)",
            "Your Maps have (192–240)% increased chance to contain a Breach (2000)",
            "Your Maps which contain Breaches have (5–10)% chance to contain three additional Breaches (800)",
            "Your Maps have +(40–60)% chance to contain a Mirror of Delirium (2000)",
            "Your Maps have (192–240)% increased chance to contain a Mirror of Delirium (2000)",
            "Your Maps have +(40–60)% chance to contain Niko (1500)",
            "Your Maps have (192–240)% increased chance to contain Niko (1500)",
            "Your Maps contain an additional Shrine (1000)",
            "Your Maps have +(15–25)% chance to contain a Shrine (1000)",
            "Your Maps contain an additional Imprisoned Monster (1000)",
            "Your Maps have +(15–25)% chance to contain an Imprisoned Monster (1000)",
            "Your Maps have +(40–60)% chance to contain an Expedition Encounter (2000)",
            "Your Maps have (192–240)% increased chance to contain an Expedition Encounter (2000)",
            "Your Maps contain an additional Harbinger (1000)",
            "Your Maps have a (15–25)% chance to contain an additional Harbinger (1000)",
            "Your Maps have +(40–60)% chance to contain The Sacred Grove (2000)",
            "Your Maps have (192–240)% increased chance to contain The Sacred Grove (2000)",
            "Your Maps have +(40–60)% chance to contain a Smuggler's Cache (2000)",
            "Your Maps have (192–240)% increased chance to contain a Smuggler's Cache (2000)",
            "Your Maps have +(40–60)% chance to contain Jun (1500)",
            "Your Maps have (192–240)% increased chance to contain Jun (1500)",
            "Your Maps have +(8–12)% chance to contain a Trial of Ascendancy (1000)",
            "Your Maps have +(40–60)% chance to contain a Legion Encounter (2000)",
            "Your Maps have (192–240)% increased chance to contain a Legion Encounter (2000)",
            "Final Map Boss in each Map has (4–6)% chance to drop an additional connected Map (1000)",
            "Your Maps have (192–240)% increased chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(40–60)% chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(40–60)% chance to contain Ritual Altars (2000)",
            "Your Maps have (192–240)% increased chance to contain Ritual Altars (2000)",
            "(8–12)% increased effect of Explicit Modifiers on your Maps (1000)",
            "Your Maps contain an additional Strongbox (1000)",
            "Your Maps have +(15–25)% chance to contain a Strongbox (1000)",
            "Your Maps have +(15–25)% chance to be haunted by a Tormented Spirit (1000)",
            "Up to 5 Rare Monsters in each of your Maps are Possessed and their Minions are Touched (1000)",
            "Your Maps are haunted by an additional Tormented Spirit (1000)",
            "Your Maps have (5–8)% chance to grant an additional Kirac Mission on Completion (1000)",
            "Your Maps have (2–2.5)% chance to grant an additional Kirac Mission on Completion (1000)",
            "(12–16)% increased Rarity of Items found in your Maps (1000)"
        ],
        suffixes: [
            "Abysses in your Maps that do not lead to an Abyssal Depths have (40–60)% increased chance to lead to a Stygian Spire (800)",
            "Abysses in your Maps have (40–60)% increased chance to lead to an Abyssal Depths (800)",
            "Abyss Cracks in your Maps have (10–20)% chance to spawn all Monsters as at least Magic (200)",
            "Abyss Pits in your Maps have (10–20)% chance to spawn all Monsters as at least Magic (200)",
            "Killing non-resident Architects in your Maps has (30–50)% chance to add an additional Upgrade Tier to the surviving Architect's Room (1500)",
            "Wild Rogue Exiles in your Maps have (75–100)% chance to be Possessed by a Tormented Spirit (1000)",
            "Your Maps that contain capturable Beasts contain (3–4) additional Yellow Beasts (800)",
            "Red Beasts captured in your Maps have a (40–60)% chance to gain a Modifier that provides a chance to not to be consumed when sacrificed at the Blood Altar (400)",
            "Red Beasts in your Maps have (16–24)% chance to appear in Pairs (300)",
            "Beyond Demons in your Maps grant (20–30)% increased Experience (250)",
            "Beyond Portals in your Maps have (25–35)% increased chance to spawn a Unique Boss (300)",
            "(20–25)% more Divination Cards found from Beyond Demons in your Maps that are followers of K'Tash (150)",
            "(20–25)% more Basic Currency Items found from Beyond Demons in your Maps that are followers of Beidat (150)",
            "(20–25)% more Unique Items found from Beyond Demons in your Maps that are followers of Ghorr (150)",
            "Blight Encounters in your Maps spawn (25–35)% more Non-Unique Monsters (700)",
            "Oils found in your Maps have (20–25)% chance to be 1 tier higher (600)",
            "Blight Monsters in your Maps take (30–40)% increased Damage (700)",
            "Breaches in your Maps have (35–45)% increased chance to contain a Boss (400)",
            "Breachstones dropped by Breach Bosses in your Maps have (3–5)% chance to be Flawless (200)",
            "Breaches in your Maps open and close #% faster Breaches in your Maps open and close #% slower (800)",
            "Breaches in your Maps have (10–15)% chance to contain a Hand of Xesht-Ula (300)",
            "Breaches in your Maps have (8–12)% increased Monster density (300)",
            "((40–60)% chance to spawn a Searing Exarch Altar when the Influence of The Searing Exarch first appears in your Maps (1000)",
            "Delirium in your Maps increases (35–50)% faster with distance from the mirror (800)",
            "Delirium Fog in your Maps lasts (10–15) additional seconds before dissipating (800)",
            "Delirium Rewards in your Maps have (8–12)% increased chance to give Delirium Orbs (400)",
            "Voltaxic Sulphite Veins and Chests in your Maps have (4–6)% chance to contain double Sulphite (500)",
            "You Gain (30–40)% increased Damage per stack of Sulphite Intoxication. (1000)",
            "Shrines in your Maps have (40–60)% chance to be guarded by an additional Pack of Monsters (1000)",
            "Monster Packs Influenced by The Shaper in your Maps have (15–25)% increased Pack Size (475)",
            "Monster Packs Influenced by The Elder in your Maps have (15–25)% increased Pack Size (475)",
            "Imprisoned Monsters in your Maps have (12–17)% chance to have 3 additional Essences (1000)",
            "Remnants in your Maps have (25–35)% chance to have an additional Suffix Modifier (400)",
            "Expeditions in your Maps have (80–100)% increased chance to be led by Tujen (250)",
            "Expeditions in your Maps have (50–60)% increased chance to be led by Dannig (250)",
            "Expedition Monsters in your Maps spawn with an additional (6–10)% of Life missing (600)",
            "Expeditions in your Maps have (80–100)% increased chance to be led by Rog (250)",
            "Expeditions in your Maps have (80–100)% increased chance to be led by Gwennen (250)",
            "Harbingers in your Maps have (20–25)% chance to be replaced by a powerful Harbinger boss (1000)",
            "Harvest Monsters in your Maps drop (12–18)% increased Quantity of Lifeforce (700)",
            "Harvests in your Maps have (8–12)% chance for the unchosen Crop to not wilt (600)",
            "The Sacred Grove in your Maps has (40–60)% chance to contain an additional Harvest (700)",
            "Smuggler's Caches in your Maps have (40–60)% increased chance to drop Contracts (1000)",
            "Smuggler's Caches drop (8–12)% more Rogue Markers for each Smuggler's Cache opened in the Area (1000)",
            "Heist Contracts found in your Maps are (70–90)% more likely to target High Value Targets (500)",
            "Heist Contracts found in your Maps are (45–65)% more likely to target Precious Targets (500)",
            "Immortal Syndicate Members in your Maps have (20–25)% increased chance to be accompanied by reinforcements (500)",
            "Immortal Syndicate Members in your Maps have (40–60)% chance to drop an additional Veiled Item (500)",
            "(40–60)% increased Rarity of Items Dropped by Immortal Syndicate Members in your Maps (500)",
            "Legion Encounters in your Maps have (100–150)% increased chance to include a Karui army (200)",
            "Legion Encounters in your Maps have (100–150)% increased chance to include an Eternal Empire army (200)",
            "Legion Encounters in your Maps have (80–120)% increased chance to include a Vaal army (200)",
            "Legion Encounters in your Maps have (75–100)% increased chance to include a Templar army (200)",
            "Legion Encounters in your Maps have (60–80)% increased chance to include a Maraketh army (200)",
            "Splinters dropped by Legion Monsters or contained in Legion Chests in your Maps have (15–20)% chance to be Duplicated (200)",
            "Splinters contained in Legion Chests in your Maps have (20–25)% chance to be Duplicated (300)",
            "Splinters dropped by Legion Monsters in your Maps have (20–25)% chance to be Duplicated (300)",
            "Legion Monsters in your Maps which have Rewards have (8–12)% chance to gain two additional Rewards, and if not have (15–20)% chance to gain one additional Reward (200)",
            "(5–10)% increased Pack Size of your Maps affected by Fortune Favours the Brave (400)",
            "(5–10)% increased Quantity of Items found in your Maps affected by Fortune Favours the Brave (400)",
            "(10–20)% increased Rarity of Items found in your Maps affected by Fortune Favours the Brave (400)",
            "Ultimatum Encounters in your Maps spawn (15–20)% increased number of Monsters (600)",
            "Ultimatum Monsters in your Maps grant (40–60)% increased Experience (500)",
            "Inscribed Ultimatums found in your Maps have (40–60)% increased chance to reward Unique Items (300)",
            "Inscribed Ultimatums found in your Maps have (40–60)% increased chance to reward Currency Items (300)",
            "Inscribed Ultimatums found in your Maps have (40–60)% increased chance to reward Divination Cards (300)",
            "Monsters Sacrificed at Ritual Altars in your Maps grant (20–25)% increased Tribute (800)",
            "Ritual Altars in your Maps spawn Monsters (15–20)% faster (800)",
            "Deferring Favours at Ritual Altars in your Maps costs (15–20)% reduced Tribute (400)",
            "Final Map Boss in each Map has (20–25)% chance to drop an additional Scarab (475)",
            "Rare Monsters in your Maps have (40–60)% increased chance to drop Scarabs per Monster Modifier affecting them (475)",
            "Currency Items from Strongboxes in your Maps are Duplicated (333)",
            "Maps from Strongboxes in your Maps are Duplicated (333)",
            "Divination Cards from Strongboxes in your Maps are Duplicated (333)",
            "Gems contained in Strongboxes in your Maps are Duplicated (333)",
            "Monsters Influenced by The Eater of Worlds in your Maps have (0.8–1.2)% chance to drop an item with an Eater of Worlds Implicit Modifier (475)",
            "(15–20)% increased chance to find Eater of Worlds Altars in your Maps (475)",
            "Items dropped by Unique Monsters have (10–15)% chance to be Corrupted (475)",
            "Vaal Side Areas in your Maps have (15–20)% chance for Rewards from Vaal Vessels to be Duplicated (475)",
            "(25–35)% increased Rarity of Maps found in your Maps (2000)"
        ]
    },
    "1x3": {
        prefixes: [],
        suffixes: []
    },
    "2x2": {
        prefixes: [
            "Your Maps have +(45–70)% chance to contain an Abyss (2000)",
            "Your Maps have (224–280)% increased chance to contain an Abyss (2000)",
            "Your Maps have +(3–5)% chance to contain an Abyss per 2% increased Pack Size (200)",
            "Your Maps have +(45–70)% chance to contain Alva (1500)",
            "Your Maps have (224–280)% increased chance to contain Alva (1500)",
            "Your Maps have a (8–12)% chance to contain (6–10) additional Rogue Exiles (200)",
            "Your Maps have a (45–70)% chance to contain an additional Rogue Exile (800)",
            "Your Maps have +(20–30)% chance to contain a Rogue Exile (1000)",
            "Your Maps have +(45–70)% chance to contain Einhar (1500)",
            "Your Maps have (224–280)% increased chance to contain Einhar (1500)",
            "(45–70)% chance for your Maps to attract Beyond Demons (1000)",
            "Your Maps have +(45–70)% chance to contain a Blight Encounter (2000)",
            "Your Maps have (224–280)% increased chance to contain a Blight Encounter (2000)",
            "Your Maps have +(45–70)% chance to contain Breaches (1600)",
            "Your Maps have (224–280)% increased chance to contain a Breach (2000)",
            "Your Maps which contain Breaches have (1–2)% chance to contain ten additional Breaches (400)",
            "Your Maps have +(45–70)% chance to contain a Mirror of Delirium (2000)",
            "Your Maps have (224–280)% increased chance to contain a Mirror of Delirium (2000)",
            "Maps found in your Maps have (3–5)% chance to have layers of Delirium (300)",
            "Your Maps have +(45–70)% chance to contain Niko (1500)",
            "Your Maps have (224–280)% increased chance to contain Niko (1500)",
            "Your Maps contain an additional Shrine (1000)",
            "Your Maps have +(20–30)% chance to contain a Shrine (1000)",
            "Your Maps contain an additional Imprisoned Monster (1000)",
            "Your Maps have +(20–30)% chance to contain an Imprisoned Monster (1000)",
            "Your Maps have +(45–70)% chance to contain an Expedition Encounter (2000)",
            "Your Maps have (224–280)% increased chance to contain an Expedition Encounter (2000)",
            "Your Maps contain an additional Harbinger (1000)",
            "Your Maps have a (20–30)% chance to contain an additional Harbinger (1000)",
            "Your Maps have +(45–70)% chance to contain The Sacred Grove (2000)",
            "Your Maps have (224–280)% increased chance to contain The Sacred Grove (2000)",
            "Your Maps have +(45–70)% chance to contain a Smuggler's Cache (2000)",
            "Your Maps have (224–280)% increased chance to contain a Smuggler's Cache (2000)",
            "Your Maps have +(45–70)% chance to contain Jun (1500)",
            "Your Maps have (224–280)% increased chance to contain Jun (1500)",
            "Your Maps have +(45–70)% chance to contain a Legion Encounter (2000)",
            "Your Maps have (224–280)% increased chance to contain a Legion Encounter (2000)",
            "(8–12)% chance on Completing your Maps to gain a free use of a random Map Crafting option (500)",
            "(3–4)% chance on Completing your Maps to gain a free use of a special Map Crafting option (500)",
            "Your Maps have (224–280)% increased chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(45–70)% chance to contain an Ultimatum Encounter (2000)",
            "Your Maps have +(45–70)% chance to contain Ritual Altars (2000)",
            "Your Maps have (224–280)% increased chance to contain Ritual Altars (1000)",
            "Your Maps contain an additional Strongbox (1000)",
            "Your Maps have +(20–30)% chance to contain a Strongbox (1000)",
            "Your Maps have +(20–30)% chance to be haunted by a Tormented Spirit (1000)",
            "Your Maps are haunted by an additional Tormented Spirit (1000)",
            "(4–6)% increased Quantity of Items found in your Maps (1000)",
            "(4–6)% increased Pack size (1000)",
            "(3–5)% increased effect of Explicit Modifiers on your Maps per 5% Map Quality (1000)",
            "(2–3)% increased effect of Explicit Modifiers on your Maps per Explicit Modifier (1000)"
        ],
        suffixes: [
            "Abyss Jewels found in Abyssal Troves or dropped by Stygian Spires in your Maps have (15–25)% chance to be Corrupted and have 5 or 6 random Modifiers (200)",
            "Abyss Jewels dropped by Abyssal Troves or Stygian Spires in your Maps have a 1% Chance to be Rare and Corrupted (400)",
            "Abyss Pits in your Maps have (14–20)% chance to spawn 5 additional Rare Monsters (200)",
            "Abyssal Troves and Stygian Spires in your Maps have (0.03–0.05)% chance to drop an Abyss Scarab (600)",
            "Abysses in your Maps that do not lead to an Abyssal Depths lead to 4 Pits if able (200)",
            "Abysses in your Maps that do not lead to an Abyssal Depths lead to at least 3 Pits if able (200)",
            "Abysses in your Maps spawn (8–12)% increased Monsters for each prior Pit in that Abyss (400)",
            "Killing resident Architects in your Maps adds their Upgrade Tier to the surviving Architect's Room (300)",
            "Incursions in your Maps contain a Vaal Flesh Merchant (300)",
            "Your Maps with Incursions always have four Incursions (300)",
            "Time gained from Kills is Doubled for Incursions in your Maps (300)",
            "Incursions in your Maps contain Cursed Treasures (300)",
            "Wild Rogue Exiles in your Maps have (40–60)% chance to have additional Rewards (1000)",
            "Beasts in your Maps are more likely to be less common varieties (450)",
            "Einhar remains in your Maps after his Mission is Complete (300)",
            "Yellow Beasts in your Maps have (12–18)% chance to be replaced with Red Beasts (450)",
            "Beasts in your Maps have a (15–20)% chance to break free Beasts which break free in your Maps gain Bestial Rage Defeating Beasts grants Hunters' Cunning per Bestial Rage on the defeated Beast (300)",
            "Slaying Enemies in your Maps has a (12–18)% increased chance to spawn a Beyond Portal (500)",
            "Gain Demonic Power on defeating a Beyond Boss in your Maps (500)",
            "Varieties of Items contained in (3–5) Blight Chests in your Maps are Lucky (800)",
            "Blight chests in your Maps have a (5–10)% chance to be openable again (400)",
            "Completing a Blight Encounter in your Maps grants all Players Blightreach (400)",
            "Blight Towers in your Maps can be Salvaged after the Blight Encounter Higher Tier Towers grant better Salvaged Rewards Salvaged Rewards are improved for each different Tower Type built during Encounter (400)",
            "Breach Bosses Defeated in your Maps have (3–5)% chance to drop a Breachstone (400)",
            "Breaches in your Maps contain (2–3) additional Clasped Hands (800)",
            "Breaches in your Maps have (2–3)% chance to contain Xesht-Ula, the Open Hand (400)",
            "Breach Boss' Clasped Hands in your Maps have (3–5)% chance to spawn a Breach Boss when opened (400)",
            "Your Maps have (10–15)% chance to award double progress towards encountering The Searing Exarch (1000)",
            "Eldritch Embers found in your Maps influenced by The Searing Exarch have (10–15)% chance to be Duplicated (1000)",
            "Delirium Encounters in your Maps have (8–12)% chance to generate three additional Reward types (300)",
            "(20–30)% increased Stack size of Simulacrum Splinters found in your Maps (800)",
            "Delirious Unique Monsters in your Maps have a (1–2)% chance to drop an additional Delirium Orb (300)",
            "Delirious Unique Monsters in your Maps have a (2–3)% chance to drop an additional Cluster Jewel (300)",
            "Voltaxic Sulphite Veins and Chests in your Maps are guarded by Sulphite-hoarding Monsters (300)",
            "You Gain +(2–3)% to all maximum Elemental Resistances per stack of Sulphite Intoxication. (900)",
            "Voltaxic Sulphite Veins and Chests found in your Maps contains Doomed Spirits (300)",
            "Shrines in your Maps are guarded by at least one Magic Pack (250)",
            "Shrines in your Maps grant a random additional Shrine Effect (250)",
            "Shrines in your Maps have (8–12)% chance to be a Covetous Shrine (500)",
            "Imprisoned Monsters in your Maps have at least 1 Essence at the highest possible tier (500)",
            "Essences found in your Maps have (25–35)% chance to be a tier higher (500)",
            "Using Remnants of Corruption on Imprisoned Monsters in your Maps replaces all Essences with one of the Essences on the Imprisoned Monster (500)",
            "(80–120)% increased Explosive Placement Range in your Maps (750)",
            "Expeditions in your Maps have +(1–2) Remnants (500)",
            "Your Maps contain (20–25)% increased number of Runic Monster Markers (750)",
            "Currency Shards dropped by Harbingers in your Maps can drop as Currency Items instead (1000)",
            "Plants Harvested in your Maps have (4–8)% chance to spawn duplicated Monsters (300)",
            "Harvested Plants in your Maps have (10–15)% chance to spawn an additional Monster (900)",
            "Lifeforce dropped by Harvest Monsters in your Maps has (10–15)% chance to be Duplicated (800)",
            "Blueprints that drop in your Maps have (10–15)% chance to be fully Revealed (500)",
            "Your Maps that contain Smuggler's Caches have a (4–6)% chance to contain 6 additional Smuggler's Caches (500)",
            "Smuggler's Caches in your Maps have (10–15)% increased chance to contain Blueprints for each Smuggler's Cache opened in the Map (500)",
            "Huck accompanies you on opening the first Smuggler's Cache in each of your Maps (500)",
            "Immortal Syndicate Members in your Maps drop (100–200)% more Items when Bargained with for Items (750)",
            "Completing your Maps grants (10–15) Intelligence for a random Immortal Syndicate Safehouse (750)",
            "Labyrinth Trials in your Maps have (20–25)% chance to award an Improved Offering to the Goddess (800)",
            "Legion Encounters in your Maps contain 2 additional Sergeants (800)",
            "Legion Encounters with a General in your Maps have both Generals (400)",
            "(0.5–0.75)% chance for Timeless Splinters to drop as Timeless Emblems instead in your Maps (800)",
            "Ultimatum Encounters in your Maps grant rewards as though you completed an additional Round (750)",
            "Ultimatum Boss drops a full stack of a random Catalyst (500)",
            "Ultimatum Rewards in your Maps have (20–25)% chance to be duplicated (750)",
            "Your Maps with Ritual Altars always have four Ritual Altars (400)",
            "Ritual Altars in your Maps allow rerolling Favours an additional time (400)",
            "Completing the final Ritual Altar in your Maps has (15–20)% chance to drop a Blood-filled Vessel (1200)",
            "Map Device has (3–5)% chance not to consume Scarabs (800)",
            "Scarabs found in your Maps are more likely to be less common varieties (800)",
            "Strongboxes in your Maps are at least Rare (300)",
            "Strongboxes in your Maps are Corrupted (300)",
            "Strongboxes opened in your Maps have (5–9)% chance to be openable again (400)",
            "Synthesised Monsters in Synthesis Maps have (20–30)% increased Pack Size (800)",
            "Monster Packs Influenced by The Eater of Worlds in your Maps have (25–35)% increased Pack Size (1000)",
            "Tormented Spirits in your Maps are more likely to be less common varieties (500)",
            "Defeating a Map Boss while Witnessed by The Maven has (10–15)% chance to count as also Witnessing an additional random Map Boss (800)"
        ]
    }
};

allModifiersData["1x2"].prefixes = allModifiersData["2x1"].prefixes;
allModifiersData["1x2"].suffixes = allModifiersData["2x1"].suffixes;
allModifiersData["1x3"].prefixes = allModifiersData["3x1"].prefixes;
allModifiersData["1x3"].suffixes = allModifiersData["3x1"].suffixes;

const modifierIdMap = { prefixes: {}, suffixes: {} };
let nextModifierId = 1;

function assignModifierId(modType, modString) {
    if (modString && !modifierIdMap[modType][modString]) {
        modifierIdMap[modType][modString] = String(nextModifierId++);
    }
}

for (const size in allModifiersData) {
    if (allModifiersData.hasOwnProperty(size)) {
        allModifiersData[size].prefixes.forEach(mod => assignModifierId('prefixes', mod));
        allModifiersData[size].suffixes.forEach(mod => assignModifierId('suffixes', mod));
    }
}

window.allModifiersData = allModifiersData;
window.modifierIdMap = modifierIdMap;
